name: Setup
description: Common setup steps

inputs:
  save-cache:
    description: Whether to save the cache
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

    - name: Cache Nix
      uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}-
        save: ${{ inputs.save-cache }}
        purge: ${{ inputs.save-cache }}
        purge-prefixes: nix-${{ runner.os }}-${{ runner.arch }}-
        purge-created: 86400

    - name: Build shell
      shell: bash
      run: nix develop --command true
